# Site
title: Shanyin's Home
subtitle: ''
description: 'Blog | Notebooks | Sharing | Everything'
keywords: 
author: 狂乱山音
language: en
timezone: 'Asia/Shanghai'

pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

show_downloads: false

logo: /assets/img/logo.png

# theme: jekyll-theme-cayman
# theme: Anatolo
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
